version: "3.9"

services:
  gubbhockey-postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=develop
      - POSTGRES_USER=develop
      - POSTGRES_DB=gubbhockey
